// Generated by CoffeeScript 1.3.1
(function() {
  var checksum, toHash;

  console.log('init');

  checksum = function(string) {
    var chk, chr, i;
    chk = 0;
    for (i in string) {
      chr = string[i];
      chk += chr.charCodeAt(0) * (i + 1);
    }
    return chk % 10;
  };

  toHash = function(input) {
    var base64, check, deflated, encoded;
    deflated = RawDeflate.deflate(input);
    base64 = Base64.toBase64(deflated);
    check = checksum(base64);
    encoded = base64 + check;
    window.location.hash = encoded;
    return true;
  };

  $(function() {
    $(".dial").knob();
    return $(window).load(function() {
      var base64, check, deflated, encoded, input, saySo;
      saySo = function(whatToSay) {
        var amplitude, pitch, speed, text, wordgap;
        text = (whatToSay != null ? whatToSay : $('#text').val()) || 'please enter your message';
        amplitude = parseInt($('#amplitude').val()) || 100;
        wordgap = parseInt($('#wordgap').val()) || 0;
        pitch = parseInt($('#pitch').val()) || 50;
        speed = parseInt($('#speed').val()) || 175;
        console.log({
          amplitude: amplitude,
          wordgap: wordgap,
          pitch: pitch,
          speed: speed
        });
        speak(text, {
          amplitude: amplitude,
          wordgap: wordgap,
          pitch: pitch,
          speed: speed
        });
        return text;
      };
      console.log('load');
      if (window.location.hash) {
        encoded = window.location.hash.replace(/^#/, '');
        base64 = encoded.slice(0, (encoded.length - 2) + 1 || 9e9);
        check = parseInt(encoded.slice(encoded.length - 1, encoded.length + 1 || 9e9));
        if (check !== checksum(base64)) {
          $('#text').val(saySo('Something got corrupted!'));
        } else {
          deflated = Base64.fromBase64(base64);
          input = RawDeflate.inflate(deflated);
          $('#text').val(input);
          window.setTimeout((function() {
            return saySo(input);
          }), 500);
        }
      } else {
        window.setTimeout((function() {
          return saySo($('#text').val());
        }), 500);
      }
      $("#text").focus(function() {
        return this.select();
      });
      $("#text").get(0).focus();
      $('#speak').on('submit', function(e) {
        console.log('submit');
        try {
          return saySo();
        } catch (error) {
          return console.log(error);
        } finally {
          return false;
        }
      });
      return $('#text').on('keyup', function(e) {
        console.log('change event');
        return toHash($('#text').val());
      });
    });
  });

}).call(this);
